import { describe, it, expect } from 'vitest'
import { PlaywrightFetchEngine } from './playwright'
import { FetchEngineContext } from '../core/context'

class TestPlaywrightEngine extends PlaywrightFetchEngine {
  public async testGetCrawlerOptions(ctx: FetchEngineContext) {
    // Manually set opts as initialize() would do
    this.opts = ctx
    return this._getSpecificCrawlerOptions(ctx)
  }
}

describe('PlaywrightFetchEngine Launch Options', () => {
  it('should pass launchOptions to crawler config in normal mode', async () => {
    const engine = new TestPlaywrightEngine()
    const launchOptions = { slowMo: 100, args: ['--no-sandbox'] }
    const ctx: FetchEngineContext = {
      id: 'test',
      engine: 'browser',
      browser: {
        engine: 'playwright',
        launchOptions: launchOptions,
      },
      internal: {} as any,
    } as any

    const options = await engine.testGetCrawlerOptions(ctx)

    expect(options.launchContext).toBeDefined()
    expect(options.launchContext?.launchOptions).toEqual(launchOptions)
  })

  it('should pass launchOptions to camoufox in antibot mode', async () => {
    const engine = new TestPlaywrightEngine()
    const launchOptions = { slowMo: 200, args: ['--disable-gpu'] }
    const ctx: FetchEngineContext = {
      id: 'test-antibot',
      engine: 'browser',
      antibot: true,
      browser: {
        engine: 'playwright',
        launchOptions: launchOptions,
      },
      internal: {} as any,
    } as any

    const options = await engine.testGetCrawlerOptions(ctx)

    expect(options.launchContext).toBeDefined()
    
    // In antibot mode, the launcher is explicitly set to firefox
    // and options are generated by camoufox
    const resultingOptions = options.launchContext?.launchOptions as any
    expect(resultingOptions).toBeDefined()
    expect(resultingOptions.slowMo).toBe(200)
    // args from camoufox include many things, but should include ours
    expect(resultingOptions.args).toEqual(expect.arrayContaining(['--disable-gpu']))
  })
})
